### PR TITLE
Backported AlternateLookup for `IEqualityComparer<T>` and `ReadOnlySpan<T>`

### LINKED ISSUE #169: Task: Backport AlternateLookup for IEqualityComparer<T> and ReadOnlySpan<T>
Microsoft came up with a powerful design for looking up dictionary and hash set keys based on `ReadOnlySpan<T>`, however they modified the compiler to provide an `allows ref struct` constraint which does not work prior to .NET 9. So, we will need to take a different approach.

Since we only need to support `ReadOnlySpan<T>` for alternate keys, we will use a narrower scope for the design.

## Design Proposal

The backport will consist of a few different parts.

### Interface

Much like the original [`IAlternateEqualityComparer<TAlternate, T>`](https://github.com/dotnet/runtime/blob/v10.0.1/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/IAlternateEqualityComparer.cs) design, we will implement the same 3 members, but shift the `ReadOnlySpan<T>` to the interface definition so it will compile on older target frameworks.

```c#
namespace J2N.Collections.Generic
{
    public interface ISpanAlternateEqualityComparer<TAlternateSpan, T>
    {
        bool Equals(ReadOnlySpan<TAlternateSpan> alternate, T other);
        int GetHashCode(ReadOnlySpan<TAlternateSpan> alternate);
        T Create(ReadOnlySpan<TAlternateSpan> alternate);
    }
}
```

Note that we can copy the documentation from upstream and alter it slightly for our use case.

### `SpanAlternateLookup<TAlternateSpan>` Structs

This will basically be a copy of the `AlternateLookup<TAlternate>` structs for `Dictionary<TKey, TValue>`, `OrderedDictionary<TKey, TValue>`, `HashSet<T>` and `OrderedHashSet<T>`, also shifting the `ReadOnlySpan<T>` to each member rather than making them purely generic.

However, unlike the original design, we don't have to conditionally compile for older target frameworks because we are targeting our own alternate comparer interface and we are not using an `allows ref struct` constraint.

```c#
namespace J2N.Collections.Generic
{
    public class Dictionary<TKey, TValue>
    {
        public SpanAlternateLookup<TAlternateKeySpan> GetSpanAlternateLookup<TAlternateKeySpan>();
        public bool TryGetSpanAlternateLookup<TAlternateKeySpan>(out SpanAlternateLookup<TAlternateKeySpan> lookup);

        public readonly struct SpanAlternateLookup<TAlternateKeySpan>
        {
            public Dictionary<TKey, TValue> Dictionary { get; }
            public TValue this[ReadOnlySpan<TAlternateKeySpan> key] { get; set; }
            public bool TryGetValue(ReadOnlySpan<TAlternateKeySpan> key, [MaybeNullWhen(false)] out TValue value);
            public bool TryGetValue(ReadOnlySpan<TAlternateKeySpan> key, [MaybeNullWhen(false)] out TKey actualKey, [MaybeNullWhen(false)] out TValue value);
            public bool ContainsKey(ReadOnlySpan<TAlternateKeySpan> key);
            public bool Remove(ReadOnlySpan<TAlternateKeySpan> key);
            public bool Remove(ReadOnlySpan<TAlternateKeySpan> key, [MaybeNullWhen(false)] out TKey actualKey, [MaybeNullWhen(false)] out TValue value);
            public bool TryAdd(ReadOnlySpan<TAlternateKeySpan> key, TValue value);
        }
    }

    public class OrderedDictionary<TKey, TValue>
    {
        public SpanAlternateLookup<TAlternateKeySpan> GetSpanAlternateLookup<TAlternateKeySpan>();
        public bool TryGetSpanAlternateLookup<TAlternateKeySpan>(out SpanAlternateLookup<TAlternateKeySpan> lookup);

        public readonly struct SpanAlternateLookup<TAlternateKeySpan>
        {
            public OrderedDictionary<TKey, TValue> Dictionary { get; }
            public TValue this[ReadOnlySpan<TAlternateKeySpan> key] { get; set; }
            public bool TryGetValue(ReadOnlySpan<TAlternateKeySpan> key, [MaybeNullWhen(false)] out TValue value);
            public bool TryGetValue(ReadOnlySpan<TAlternateKeySpan> key, [MaybeNullWhen(false)] out TKey actualKey, [MaybeNullWhen(false)] out TValue value);
            public bool ContainsKey(ReadOnlySpan<TAlternateKeySpan> key);
            public bool Remove(ReadOnlySpan<TAlternateKeySpan> key);
            public bool Remove(ReadOnlySpan<TAlternateKeySpan> key, [MaybeNullWhen(false)] out TKey actualKey, [MaybeNullWhen(false)] out TValue value);
            public int IndexOf(ReadOnlySpan<TAlternateKeySpan> key);
            public bool TryAdd(ReadOnlySpan<TAlternateKeySpan> key, TValue value);
        }
    }

    public class HashSet<T>
    {
        public SpanAlternateLookup<TAlternateSpan> GetSpanAlternateLookup<TAlternateSpan>();
        public bool TryGetSpanAlternateLookup<TAlternateSpan>(out SpanAlternateLookup<TAlternateSpan> lookup);

        public readonly struct SpanAlternateLookup<TAlternateSpan>
        {
            public HashSet<T> Set { get; }
            public bool Add(ReadOnlySpan<TAlternateSpan> item);
            public bool Remove(ReadOnlySpan<TAlternateSpan> item);
            public bool Contains(ReadOnlySpan<TAlternateSpan> item);
            public bool TryGetValue(ReadOnlySpan<TAlternateSpan> equalValue, [MaybeNullWhen(false)] out T actualValue);
        }
    }

    public class OrderedHashSet<T>
    {
        public SpanAlternateLookup<TAlternateSpan> GetSpanAlternateLookup<TAlternateSpan>();
        public bool TryGetSpanAlternateLookup<TAlternateSpan>(out SpanAlternateLookup<TAlternateSpan> lookup);

        public readonly struct SpanAlternateLookup<TAlternateSpan>
        {
            public OrderedHashSet<T> Set { get; }
            public bool Add(ReadOnlySpan<TAlternateSpan> item);
            public bool Remove(ReadOnlySpan<TAlternateSpan> item);
            public bool Contains(ReadOnlySpan<TAlternateSpan> item);
            public bool TryGetValue(ReadOnlySpan<TAlternateSpan> equalValue, [MaybeNullWhen(false)] out T actualValue);
            public int IndexOf(ReadOnlySpan<TAlternateSpan> value);
        }
    }
}
```

### CollectionMarshal Support

Much like the original design, we will need new members on `CollectionMarshal` for supporting low-level code.

```c#
namespace J2N.Runtime.InteropServices
{
    public static class CollectionMarshal
    {
        public static ref TValue GetValueRefOrNullRef<TKey, TValue, TAlternateKeySpan>(Dictionary<TKey, TValue>.SpanAlternateLookup<TAlternateKeySpan> dictionary, ReadOnlySpan<TAlternateKeySpan> key);
        public static ref TValue GetValueRefOrNullRef<TKey, TValue, TAlternateKeySpan>(OrderedDictionary<TKey, TValue>.SpanAlternateLookup<TAlternateKeySpan> dictionary, ReadOnlySpan<TAlternateKeySpan> key);

        public static ref TValue? GetValueRefOrAddDefault<TKey, TValue, TAlternateKeySpan>(Dictionary<TKey, TValue>.SpanAlternateLookup<TAlternateKeySpan> dictionary, ReadOnlySpan<TAlternateKeySpan> key, out bool exists);
        public static ref TValue? GetValueRefOrAddDefault<TKey, TValue, TAlternateKeySpan>(OrderedDictionary<TKey, TValue>.SpanAlternateLookup<TAlternateKeySpan> dictionary, ReadOnlySpan<TAlternateKeySpan> key, out bool exists);
    }
}
```

### String Comparer Wrappers

We will also need to add support for the `ISpanAlternateEqualityComparer<TAlternateSpan, T>` interface in our internal wrappers. This should be all that is required to support the BCL string comparers, but we will need tests to confirm the functionality works.

```c#
namespace J2N.Collections.Generic
{
    internal class NonRandomizedStringEqualityComparer
    {
        private sealed class OrdinalComparer : NonRandomizedStringEqualityComparer, ISpanAlternateEqualityComparer<char, string?>
#if FEATURE_IALTERNATEEQUALITYCOMPARER
            , IAlternateEqualityComparer<ReadOnlySpan<char>, string?>
#endif
        {
            int ISpanAlternateEqualityComparer<char, string?>.GetHashCode(ReadOnlySpan<char> span);
            bool ISpanAlternateEqualityComparer<char, string?>.Equals(ReadOnlySpan<char> span, string? target);
            string ISpanAlternateEqualityComparer<char, string?>.Create(ReadOnlySpan<char> span);
        }

        private sealed class OrdinalIgnoreCaseComparer : NonRandomizedStringEqualityComparer, ISpanAlternateEqualityComparer<char, string?>
#if FEATURE_IALTERNATEEQUALITYCOMPARER
            , IAlternateEqualityComparer<ReadOnlySpan<char>, string?>
#endif
        {
            int ISpanAlternateEqualityComparer<char, string?>.GetHashCode(ReadOnlySpan<char> span);
            bool ISpanAlternateEqualityComparer<char, string?>.Equals(ReadOnlySpan<char> span, string? target);
            string ISpanAlternateEqualityComparer<char, string?>.Create(ReadOnlySpan<char> span);
        }
    }

    internal class RandomizedStringEqualityComparer
    {
        private sealed class OrdinalComparer : NonRandomizedStringEqualityComparer, ISpanAlternateEqualityComparer<char, string?>
#if FEATURE_IALTERNATEEQUALITYCOMPARER
            , IAlternateEqualityComparer<ReadOnlySpan<char>, string?>
#endif
        {
            int ISpanAlternateEqualityComparer<char, string?>.GetHashCode(ReadOnlySpan<char> alternate);
            bool ISpanAlternateEqualityComparer<char, string?>.Equals(ReadOnlySpan<char> alternate, string? other);
            string ISpanAlternateEqualityComparer<char, string?>.Create(ReadOnlySpan<char> span);
        }

        private sealed class OrdinalIgnoreCaseComparer : NonRandomizedStringEqualityComparer, ISpanAlternateEqualityComparer<char, string?>
#if FEATURE_IALTERNATEEQUALITYCOMPARER
            , IAlternateEqualityComparer<ReadOnlySpan<char>, string?>
#endif
        {
            int ISpanAlternateEqualityComparer<char, string?>.GetHashCode(ReadOnlySpan<char> alternate);
            bool ISpanAlternateEqualityComparer<char, string?>.Equals(ReadOnlySpan<char> alternate, string? other);
            string ISpanAlternateEqualityComparer<char, string?>.Create(ReadOnlySpan<char> span);
        }
    }
}
```

## Related Work

This is being described here to put it into context, but this work should not be part of this PR.

1. Add AlternateLookup for `IComparer<T>` and `ReadOnlySpan<T>` - `SortedDictionary<TKey, TValue>` and `SortedSet<T>` depend on `IComparer<T>` to do lookups, so we will need an `ISpanAlternateComparer<TAlternateSpan, T>` interface to handle that case. The `UnicodeSet` type depends on this and needs to support `ReadOnlySpan<char>`.
2. Extension methods on `IDictionary<TKey, TValue>` and `ISet<T>` for alternate lookup. I am still debating whether it makes more sense to put these in J2N and have them gracefully degrade for unsupported collection types or to put these in Lucene.NET and ICU4N and have them throw `NotSupportedException` if we accidentally plug in an unsupported collection type.

### PR DESCRIPTION
**Pull request by NightOwl888**
Fixes #169.

This adds support for .NET 8 and prior for `ReadOnlySpan<T>` alternate lookup and adds wrappers for all built-in `System.StringComparer` options. It is effectively a duplicate of the functionality that was added in .NET 9+, but with a simplified design that will compile on older target frameworks that don't support the `allows ref struct` generic constraint.

There were also some bugs in the `OrderedDictionary<TKey, TValue>` and `OrderedHashSet<T>` regarding how the internal comparer wrappers are treated so they will act correctly as adapter classes for built-in `StringComparer` implementations that were addressed.

In addition, the implementation is consistent across `Dictionary<TKey, TValue>`, `OrderedDictionary<TKey, TValue>`, `HashSet<T>` and `OrderedHashSet<T>`, which forms a backbone for supporting `ReadOnlySpan<char>` overloads for collections containing strings. But, we will need to add support for alternate lookup on `SortedDictionary<TKey, TValue>` and `SortedSet<T>` #170 for consistent usage across the most common collection types.

### CODE REVIEW

File: src/J2N/Collections/Generic/OrderedDictionary.cs [hunk 1]
```diff
@@ -2850,6 +2851,475 @@ public bool TryAdd([AllowNull] TAlternateKey key, TValue value)
...
+        {
+            /// <summary>Initialize the instance. The dictionary must have already been verified to have a compatible comparer.</summary>
+            internal SpanAlternateLookup(OrderedDictionary<TKey, TValue> dictionary)
+            {
+                Debug.Assert(dictionary is not null);
+                Debug.Assert(IsCompatibleKey(dictionary!)); // [!]: asserted above
+                Dictionary = dictionary!; // [!]: asserted above
+            }
+
+            /// <summary>Gets the <see cref="Dictionary{TKey, TValue}"/> against which this instance performs operations.</summary>
```
Comment (paulirwin) [inline src/J2N/Collections/Generic/OrderedDictionary.cs]: Comment mentions `Dictionary{TKey, TValue}` but should be `OrderedDictionary{TKey, TValue}`

**Review by paulirwin — APPROVED** [review]
Looks good, minor comments added

File: src/J2N/Collections/Generic/Dictionary.cs [hunk 2]
```diff
@@ -2573,6 +2586,433 @@ public bool TryAdd([AllowNull] TAlternateKey key, TValue value)
...
+            internal ref TValue FindValue(ReadOnlySpan<TAlternateKeySpan> key, [MaybeNullWhen(false)] out TKey actualKey)
+            {
+                Dictionary<TKey, TValue> dictionary = Dictionary;
+
+                ref Entry entry = ref Unsafe.NullRef<Entry>();
+                if (dictionary._buckets != null)
+                {
+                    Debug.Assert(dictionary._entries != null, "expected entries to be != null");
+
+                    ISpanAlternateEqualityComparer<TAlternateKeySpan, TKey> comparer = GetAlternateComparer(dictionary); // J2N: Moved within null check, since we don't need to look this up for null keys
```
Comment (NightOwl888) [inline src/J2N/Collections/Generic/Dictionary.cs]: Minor issue- we should remove the comment here because this is no longer inside of a null check and this overload does not accept null keys.

File: src/J2N/Collections/Generic/OrderedDictionary.cs [hunk 3]
```diff
@@ -1327,7 +1327,9 @@ private void Resize(int newSize, bool forceNewHashCodes = false)
             {
                 // Store the original randomized comparer instead of the non-randomized one.
                 Debug.Assert(_comparer is NonRandomizedStringEqualityComparer);
-                IEqualityComparer<TKey> comparer = _comparer = (IEqualityComparer<TKey>)((NonRandomizedStringEqualityComparer)_comparer!).GetUnderlyingEqualityComparer(); // [!]: asserted above
+                // J2N: We must use the internal RandomizedEqualityComparer rather than the underlying comparer here, since we have custom
```
Comment (NightOwl888) [inline src/J2N/Collections/Generic/OrderedDictionary.cs:1330]: Minor issue - this should be NonRandomizedEqualityComparer, not RandomizedEqualityComparer

File: src/J2N/Collections/Generic/OrderedHashSet.cs [hunk 4]
```diff
@@ -1717,7 +1718,9 @@ private void Resize(int newSize, bool forceNewHashCodes = false)
             {
                 // Store the original randomized comparer instead of the non-randomized one.
                 Debug.Assert(_comparer is NonRandomizedStringEqualityComparer);
-                IEqualityComparer<T> comparer = _comparer = (IEqualityComparer<T>)((NonRandomizedStringEqualityComparer)_comparer!).GetUnderlyingEqualityComparer(); // [!]: asserted above
+                // J2N: We must use the internal RandomizedEqualityComparer rather than the underlying comparer here, since we have custom
```
Comment (NightOwl888) [inline src/J2N/Collections/Generic/OrderedHashSet.cs:1721]: Minor issue - this should be NonRandomizedEqualityComparer rather than RandomizedEqualityComparer

File: src/J2N/Collections/Generic/OrderedDictionary.cs (hunk 3 above)
Comment (NightOwl888) [reply src/J2N/Collections/Generic/OrderedDictionary.cs:1330]: Oops, the comment is correct - it is looking up the RandomizedEqualityComparer from the NonRandomizedEqualityComparer. The end result is indeed RandomizedEqualityComparer.

File: src/J2N/Collections/Generic/OrderedHashSet.cs (hunk 4 above)
Comment (NightOwl888) [reply src/J2N/Collections/Generic/OrderedHashSet.cs:1721]: Oops, the comment is correct - it is looking up the RandomizedEqualityComparer from the NonRandomizedEqualityComparer. The end result is indeed RandomizedEqualityComparer.
