### PR TITLE
Fixed incorrect use of `[MaybeNull]`, #155

### LINKED ISSUE #155: Incorrect usage of `[MaybeNull]`
There are several places in the codebase (I first found it in JCG.Dictionary) where a parameter is incorrectly annotated with `[AllowNull, MaybeNull]` which creates incorrect nullability checking for users of the library. This was ostensibly done to indicate that i.e. the dictionary key value can be null (for which `AllowNull` is correct), but the extra `MaybeNull` causes the C# compiler to think that the key passed into it could be null after the method is called, when it definitively is not null.

Example:
```c#
string k = "foo"; // definitively not null
if (dict.TryGetValue(k, out var v))
{
    // assuming `doSomething`'s parameter is non-nullable
    doSomething(k); // "Possible null reference argument" warning
}
```

Removing the `MaybeNull` attribute where it's not needed should fix this issue. We should audit the codebase for all places where it might be used incorrectly (LurchTable is at least one other case I found) and fix those as well.

### PR DESCRIPTION
**Pull request by paulirwin**
Fixes #155.

This fixes some incorrect uses of `[MaybeNull]` that were causing the C# compiler to think that keys that were definitively not null were possibly null after calling i.e. `TryGetValue`. `[MaybeNull]` is a [postcondition attribute](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis#postconditions-maybenull-and-notnull), so it only applies after the method is called, if that method is making some determination about the value being null.

For some private members, where it didn't cause additional compiler warnings, I chose to replace `[AllowNull, MaybeNull]` with `T?`. This is simpler and accomplishes the same thing.

For the `Current` enumerator property, I added a nullable suppression operator (`!`) to its field access, which matches the style of how .NET does it (i.e. [this example](https://github.com/dotnet/runtime/blob/c01656e6415a0a6d55d93932cba2f6861a042de5/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/Dictionary.cs#L2051))

### CODE REVIEW

File: src/J2N/Collections/Generic/EnumerableHelpers.cs [hunk 1]
```diff
@@ -19,7 +19,7 @@ internal static partial class EnumerableHelpers
     {
         /// <summary>Calls Reset on an enumerator instance.</summary>
         /// <remarks>Enables Reset to be called without boxing on a struct enumerator that lacks a public Reset.</remarks>
-        internal static void Reset<T>(ref T enumerator) where T : IEnumerator => enumerator.Reset();
+        internal static void Reset<T>(in T enumerator) where T : IEnumerator => enumerator.Reset();
```
Comment (NightOwl888) [inline src/J2N/Collections/Generic/EnumerableHelpers.cs]: This was `ref` upstream. Let's revert this. Most enumerators are structs, and removing the ref will cause the instance to be copied.

https://github.com/dotnet/runtime/blob/v10.0.0-rc.2.25502.107/src/libraries/Common/src/System/Collections/Generic/EnumerableHelpers.cs#L15

**Review by NightOwl888 — CHANGES_REQUESTED** [review]
Thanks for the PR.

`LurchTable<TKey, TValue>` has many failing tests now. I think they are failing due to the change from `ref` to `in`, which is likely affecting thread safety. [`LurchTable<TKey, TValue>` is a 3rd party implementation](http://csharptest.net/1279/introducing-the-lurchtable-as-a-c-version-of-linkedhashmap/index.html), and it would probably be best leave it as it was upstream for the most part. It was made before nullable reference types were a thing, so we have to improvise on that part.

**Review by NightOwl888 — APPROVED** [review]
Thanks for fixing that. This looks good.
